#!/usr/bin/with-contenv bash

echo "**** Changing Extension Gallery ****"
python3 -c 'exec("""\nimport json\nimport os\n\nwith open("/app/code-server/lib/vscode/product.json", "r") as json_file:\n    json_dict = json.load(json_file)\n    json_dict\n    json_dict["extensionsGallery"] = {\n        "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",\n        "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",\n        "itemUrl": "https://marketplace.visualstudio.com/items",\n    }\n\nos.remove("/app/code-server/lib/vscode/product.json")\nwith open("/app/code-server/lib/vscode/product.json", "w") as out_file:\n    json.dump(json_dict, out_file, indent=4)\n""")'
